name: Release and Deploy PWA

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create or update tag
        run: |
          git tag -f Apk
          git push -f origin Apk

  delete-old-release:
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - name: Delete previous release and tag
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: Apk
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  build-and-upload:
    needs: delete-old-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Upload build to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Apk
          files: dist/LoremIpsum/browser/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
